import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Filecoin Name System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-4'>
        <div className='flex justify-start pt-24'>
          <div>
            <h2 className='text-3xl'>f1abjxfbp274xpdqcpuaykwkfb43omjotacm2p3za</h2>
            <p>Too long to remember ? </p>
            <img src="/angry.png" alt="" className='h-24' />
          </div>
        </div>
        <div className='flex justify-end pt-24'>
          <div className='mb-20'>
            <h2 className='text-3xl'>vitalik.fil</h2>
            <p>Don't worry, we've got human readable names for your address</p>
            <div className='flex justify-center'>
              <img src="/smile.png" alt="" className='h-24' />
            </div>
            
          </div>
        </div>
        <div className="flex justify-center h-40">
          <button>Grab a name</button>
        </div>
        <div className='flex justify-start px-14'>
          <div className='w-[40%] pb-8'>
            <h3>Why names instead of addresses?</h3>
            <p>
              Names are easy to remember than 20 characters addresses. You get to look up easily for an address or a validator. 
              One more benefit, names are less error prone.
            </p>
          </div>
        </div>

        <div className='flex justify-end px-14'>
          <div className='w-[40%]'>
            <h3>Own your handle</h3>
            <p>
              Once you have purchassed a handle, you're free to use it for the amount of time that you have paid for. You can also
              set a second address to help you manage it.
            </p>
          </div>
        </div>

        <div className="flex justify-center h-40">
          <button>Grab a name</button>
        </div>
        <Footer/>
      </main>
    </>
  )
}

